/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

class JSI_EXPORT RNCAnyHeaderEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  

  
};
class JSI_EXPORT RNCClassicsHeaderEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  

  
};
class JSI_EXPORT RNCDefaultHeaderEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  

  
};
class JSI_EXPORT RNCMaterialHeaderEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  

  
};
class JSI_EXPORT SmartRefreshLayoutEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnRefresh {
      
    };

  struct OnHeaderPulling {
      Float percent;
    Float offset;
    Float headerHeight;
    };

  struct OnHeaderReleasing {
      Float percent;
    Float offset;
    Float headerHeight;
    };

  struct OnPullDownToRefresh {
      
    };

  struct OnReleaseToRefresh {
      
    };

  struct OnHeaderReleased {
      
    };

  void onRefresh(OnRefresh value) const;

  void onHeaderPulling(OnHeaderPulling value) const;

  void onHeaderReleasing(OnHeaderReleasing value) const;

  void onPullDownToRefresh(OnPullDownToRefresh value) const;

  void onReleaseToRefresh(OnReleaseToRefresh value) const;

  void onHeaderReleased(OnHeaderReleased value) const;
};
class JSI_EXPORT RNCStoreHouseHeaderEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  

  
};

} // namespace react
} // namespace facebook
