
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <jsi/jsi.h>
#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>
#include <react/renderer/graphics/Color.h>

namespace facebook {
namespace react {

class JSI_EXPORT RNCAnyHeaderProps final : public ViewProps {
 public:
  RNCAnyHeaderProps() = default;
  RNCAnyHeaderProps(const PropsParserContext& context, const RNCAnyHeaderProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string primaryColor{};
};

class JSI_EXPORT RNCClassicsHeaderProps final : public ViewProps {
 public:
  RNCClassicsHeaderProps() = default;
  RNCClassicsHeaderProps(const PropsParserContext& context, const RNCClassicsHeaderProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string primaryColor{};
  std::string accentColor{};
};

class JSI_EXPORT RNCDefaultHeaderProps final : public ViewProps {
 public:
  RNCDefaultHeaderProps() = default;
  RNCDefaultHeaderProps(const PropsParserContext& context, const RNCDefaultHeaderProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string primaryColor{};
  std::string accentColor{};
};

class JSI_EXPORT RNCMaterialHeaderProps final : public ViewProps {
 public:
  RNCMaterialHeaderProps() = default;
  RNCMaterialHeaderProps(const PropsParserContext& context, const RNCMaterialHeaderProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  
};

struct SmartRefreshLayoutAutoRefreshStruct {
  bool refresh;
  Float time;
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, SmartRefreshLayoutAutoRefreshStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_refresh = map.find("refresh");
  if (tmp_refresh != map.end()) {
    fromRawValue(context, tmp_refresh->second, result.refresh);
  }
  auto tmp_time = map.find("time");
  if (tmp_time != map.end()) {
    fromRawValue(context, tmp_time->second, result.time);
  }
}

static inline std::string toString(const SmartRefreshLayoutAutoRefreshStruct &value) {
  return "[Object SmartRefreshLayoutAutoRefreshStruct]";
}
class JSI_EXPORT SmartRefreshLayoutProps final : public ViewProps {
 public:
  SmartRefreshLayoutProps() = default;
  SmartRefreshLayoutProps(const PropsParserContext& context, const SmartRefreshLayoutProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  bool overScrollBounce{true};
  bool enableRefresh{true};
  Float headerHeight{0.0};
  bool overScrollDrag{true};
  bool pureScroll{false};
  Float dragRate{0.5};
  Float maxDragRate{2.0};
  SharedColor primaryColor{};
  SmartRefreshLayoutAutoRefreshStruct autoRefresh{};
};

class JSI_EXPORT RNCStoreHouseHeaderProps final : public ViewProps {
 public:
  RNCStoreHouseHeaderProps() = default;
  RNCStoreHouseHeaderProps(const PropsParserContext& context, const RNCStoreHouseHeaderProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::string textColor{};
  std::string text{};
  int fontSize{25};
  Float lineWidth{0.0};
  Float dropHeight{0.0};
};

} // namespace react
} // namespace facebook
