
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "EventEmitters.h"
#include "Props.h"
#include "States.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char RNCAnyHeaderComponentName[];

/*
 * `ShadowNode` for <RNCAnyHeader> component.
 */
using RNCAnyHeaderShadowNode = ConcreteViewShadowNode<
    RNCAnyHeaderComponentName,
    RNCAnyHeaderProps,
    RNCAnyHeaderEventEmitter,
    RNCAnyHeaderState>;

JSI_EXPORT extern const char RNCClassicsHeaderComponentName[];

/*
 * `ShadowNode` for <RNCClassicsHeader> component.
 */
using RNCClassicsHeaderShadowNode = ConcreteViewShadowNode<
    RNCClassicsHeaderComponentName,
    RNCClassicsHeaderProps,
    RNCClassicsHeaderEventEmitter,
    RNCClassicsHeaderState>;

JSI_EXPORT extern const char RNCDefaultHeaderComponentName[];

/*
 * `ShadowNode` for <RNCDefaultHeader> component.
 */
using RNCDefaultHeaderShadowNode = ConcreteViewShadowNode<
    RNCDefaultHeaderComponentName,
    RNCDefaultHeaderProps,
    RNCDefaultHeaderEventEmitter,
    RNCDefaultHeaderState>;

JSI_EXPORT extern const char RNCMaterialHeaderComponentName[];

/*
 * `ShadowNode` for <RNCMaterialHeader> component.
 */
using RNCMaterialHeaderShadowNode = ConcreteViewShadowNode<
    RNCMaterialHeaderComponentName,
    RNCMaterialHeaderProps,
    RNCMaterialHeaderEventEmitter,
    RNCMaterialHeaderState>;

JSI_EXPORT extern const char SmartRefreshLayoutComponentName[];

/*
 * `ShadowNode` for <SmartRefreshLayout> component.
 */
using SmartRefreshLayoutShadowNode = ConcreteViewShadowNode<
    SmartRefreshLayoutComponentName,
    SmartRefreshLayoutProps,
    SmartRefreshLayoutEventEmitter,
    SmartRefreshLayoutState>;

JSI_EXPORT extern const char RNCStoreHouseHeaderComponentName[];

/*
 * `ShadowNode` for <RNCStoreHouseHeader> component.
 */
using RNCStoreHouseHeaderShadowNode = ConcreteViewShadowNode<
    RNCStoreHouseHeaderComponentName,
    RNCStoreHouseHeaderProps,
    RNCStoreHouseHeaderEventEmitter,
    RNCStoreHouseHeaderState>;

} // namespace react
} // namespace facebook
