/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateH.js
 */
#pragma once

#ifdef ANDROID
#include <folly/dynamic.h>
#include <react/renderer/mapbuffer/MapBuffer.h>
#include <react/renderer/mapbuffer/MapBufferBuilder.h>
#endif

namespace facebook {
namespace react {

class RNCAnyHeaderState {
public:
  RNCAnyHeaderState() = default;

#ifdef ANDROID
  RNCAnyHeaderState(RNCAnyHeaderState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class RNCClassicsHeaderState {
public:
  RNCClassicsHeaderState() = default;

#ifdef ANDROID
  RNCClassicsHeaderState(RNCClassicsHeaderState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class RNCDefaultHeaderState {
public:
  RNCDefaultHeaderState() = default;

#ifdef ANDROID
  RNCDefaultHeaderState(RNCDefaultHeaderState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class RNCMaterialHeaderState {
public:
  RNCMaterialHeaderState() = default;

#ifdef ANDROID
  RNCMaterialHeaderState(RNCMaterialHeaderState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class SmartRefreshLayoutState {
public:
  SmartRefreshLayoutState() = default;

#ifdef ANDROID
  SmartRefreshLayoutState(SmartRefreshLayoutState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class RNCStoreHouseHeaderState {
public:
  RNCStoreHouseHeaderState() = default;

#ifdef ANDROID
  RNCStoreHouseHeaderState(RNCStoreHouseHeaderState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

} // namespace react
} // namespace facebook